### ISSUE TITLE
Nzbhydra incompatibility

### ISSUE THREAD

**Issue by iamneur0** [nzbdav-dev/nzbdav-public#127]
I tried adding Nzbdav to nzbhydra but i keep getting this error. Prowlarr however has no issues.

Is it possible adding nzbhydra support?

![image](https://github.com/user-attachments/assets/4cdc55ec-1697-4935-8bef-3f9bc8c16cd1)

**Comment by DanaramaPyjama** [comment]
Yeah I also added my local NZB DAV to my Local Hydra and got a 500 error.

The logs didn't say much~:

`POST /api?apikey=<redacted>&output=json&mode=addfile&nzbname=<redacted>.nzb&priority=-100&cat=TV%20SD 500 - - 57.294 ms`

This is when I use the "Send to SAB" function in Hydra.  All the details are correct

<img width="537" height="196" alt="Image" src="https://github.com/user-attachments/assets/e4497878-7c27-4b31-9a90-a2c7c29cfc25" />

**Comment by DanaramaPyjama** [comment]
Oh false alarm maybe?  Changing advanced settings to "Send link" it does work.

**Comment by di5c0rduser** [comment]
> Oh false alarm maybe? Changing advanced settings to "Send link" it does work.

Thanks. I used to get the exact same issue like yours. Changing it to Send Link option worked for me too.

**Comment by huplo-glitch** [comment]
I've managed to change the advanced settings to "Send Link", but I still receive the undefined error message even after deleting and re-adding in the downloader config after clicking on "Send to SABnzb". Am I missing something?

<img width="1222" height="1638" alt="Image" src="https://github.com/user-attachments/assets/6a843e32-5183-4b43-a7ca-027a9f7e24b9" />

<img width="1270" height="306" alt="Image" src="https://github.com/user-attachments/assets/3d49d3cd-9571-421b-8ac4-0de3285b4b1d" />

Docker logs for the nzbhydra2 indicate the API of nzbdav is returning "Invalid Mode":

> Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"status":false,"error":"Invalid mode"}"] with root cause
> 
> org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"status":false,"error":"Invalid mode"}"
>         at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
>         at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
>         at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
>         at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915)
>         at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864)
>         at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:804)
>         at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:396)
>         at org.nzbhydra.downloading.downloaders.sabnzbd.Sabnzbd.getCategories(Sabnzbd.java:351)
>         at org.nzbhydra.downloading.downloaders.DownloaderWeb.getCategories(DownloaderWeb.java:72)
>         at org.nzbhydra.auth.ThreadLoggingFilter.doFilterInternal(ThreadLoggingFilter.java:39) [19 skipped]
>         at org.nzbhydra.auth.HydraAnonymousAuthenticationFilter.doFilter(HydraAnonymousAuthenticationFilter.java:101) [3 skipped]
>         at org.nzbhydra.auth.AsyncSupportFilter.doFilterInternal(AsyncSupportFilter.java:35) [2 skipped]
>         at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) [12 skipped]
>         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) [20 skipped]
>         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)

On the nzbdav docker log, it reveals nzbdav lacks the get_cats as a mode (which is indeed supported by the SABnzb API):-

> GET /api?apikey=[redacted]&output=json&mode=get_cats 400 - - 38.463 ms
> GET /api?apikey=[redacted]&output=json&mode=get_cats 400 - - 8.106 ms
> GET /api?apikey=[redacted]&output=json&mode=get_cats 400 - - 6.136 ms

Any support or pointers @nzbdav-dev will be greatly appreciated :)

**Comment by golmar87** [comment]
@huplo-glitch , NZBHydra asks for categories when downloading/sending. It seems NZBDav doesn't know how to handle this request.
Set the "Default Category" in nzbhydra downloader setting to "Use original category" or "uncategorized" or whatever (without quotation marks), so nzbhydra doesn't ask for categories. This solved the Problem for me (plus "send link" instead of upload nzb)

**Comment by huplo-glitch** [comment]
> [@huplo-glitch](https://github.com/huplo-glitch) , NZBHydra asks for categories when downloading/sending. It seems NZBDav doesn't know how to handle this request. Set the "Default Category" in nzbhydra downloader setting to "Use original category" or "uncategorized" or whatever (without quotation marks), so nzbhydra doesn't ask for categories. This solved the Problem for me (plus "send link" instead of upload nzb)

I did try this at the time of posting, which changed the error from 400 to 5XX if I recall correctly and thus gave up and moved to Powlarr. However, when I get the chance will revisit to see if this solves it. Thanks!

**Comment by nzbdav-dev** [comment]
I opened [this issue](https://github.com/theotherp/nzbhydra2/issues/1037) on nzbhydra's repo and it looks like it's resolved now. 

I tried it on the latest `lscr.io/linuxserver/nzbhydra2` image and seems nzbhydra is able to send nzbs to nzbdav now.

Could someone else verify and let me know if this issue can be closed?

**Comment by huplo-glitch** [comment]
> I opened [this issue](https://github.com/theotherp/nzbhydra2/issues/1037) on nzbhydra's repo and it looks like it's resolved now.
> 
> I tried it on the latest `lscr.io/linuxserver/nzbhydra2` image and seems nzbhydra is able to send nzbs to nzbdav now.
> 
> Could someone else verify and let me know if this issue can be closed?

Thanks @nzbdav-dev and @golmar87! I've pulled the latest hydra2 docker image and still the same error message (undefined) if "Default Category" is not set. However, if I set the category, I receive the same error message which is:-

> Hydra2 API endpoint: /internalapi/downloader/addNzbs
> {
>   "successful" : false,
>   "message" : "Error while adding NZB(s): I/O error on POST request for \"http://localhost:3000/api\": timeout",
>   "addedIds" : [ ],
>   "missedIds" : [ 1555580569744413397 ]
> }

<img width="904" height="250" alt="Image" src="https://github.com/user-attachments/assets/0531366c-461c-44f2-9ca7-ab2194ed1d9f" />

<img width="1768" height="1332" alt="Image" src="https://github.com/user-attachments/assets/7f9ca9b1-857d-44dd-8869-4f90f31009a5" />

It is worth noting connectivity does work as it's able to validate my credentials (in fact it told me off for having the incorrect API key until I fixed it), though the above is pointing to some connectivity issue it seems. I am using gluetun (everything proxies through it). Also worth noting is works perfectly fine with Prowlarr.

Here's an extract of my Dockerfile in case it helps:-

```yaml
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8089:8080" # Sabnzbd
      - "3001:3000" #nzbdav
      - "3001:3000/udp"
      - "5076:5076" #Hydra2
    volumes:
      - ./etc/localtime:/etc/localtime:ro
      - ./mnt/NASData/AppsConfig/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=[redacted]
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=[redacted]
      - WIREGUARD_ADDRESSES=[redacted]
      - SERVER_COUNTRIES=[redacted]
      - UPDATER_PERIOD=24h
      - DNS_ADDRESS=127.0.0.11
  nzbdav:
    image: nzbdav/nzbdav:latest
    container_name: nzbdav
    network_mode: service:gluetun
    restart: unless-stopped
#    ports:
#      - "3001:3000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./nzbdav:/config
      - ./data/completed-downloads:/mnt/data/completed-downloads
    depends_on:
      - gluetun

  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./nzbhydra2/data:/config
      #- /path/to/downloads:/downloads #optional
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr/data:/config
```

**Comment by nzbdav-dev** [comment]
@huplo-glitch, if you docker exec into the nzbhydra container, are you able to run this successfully from within the nzbhydra container?

```
curl "http://localhost:3000/api?mode=queue&apikey=insert-nzbdav-api-key"
```

If this doesn't work, it would indicate a networking error.

**Comment by huplo-glitch** [comment]
> [@huplo-glitch](https://github.com/huplo-glitch), if you docker exec into the nzbhydra container, are you able to run this successfully from within the nzbhydra container?
> 
> ```
> curl "http://localhost:3000/api?mode=queue&apikey=insert-nzbdav-api-key"
> ```
> 
> If this doesn't work, it would indicate a networking error.

Output below - as I say, I would be surprised if it was connectivity given Hydra2 was able to successful validate the credentials and even returned a error based on the response from nzbdav when the categories field was not set (i.e due to the lack of sabnzb API support from nzbdav).

> huplo@us:$ docker exec -it nzbhydra2 sh
> curl "http://localhost:3000/api?mode=queue&apikey=[redacted]"
> {"queue":{"paused":false,"slots":[],"noofslots":0},"status":true,"error":null}#s
> curl "http://localhost:3000/api?mode=queue&apikey=[redacted]"
> {"queue":{"paused":false,"slots":[],"noofslots":0},"status":true,"error":null}#s

**Comment by huplo-glitch** [comment]
In case it's useful here's the output from nzbhydra2's docker logs

> huplo@us:$ docker logs nzbhydra2
> 2026-01-17 22:09:25.152  INFO --- [http-nio-0.0.0.0-5] org.nzbhydra.searching.SearchWeb         : [ID: 96325, Host: 172.20.0.1] Web search took 471ms
> 2026-01-17 22:09:40.749 ERROR --- [http-nio-0.0.0.0-5] o.n.downloading.downloaders.Downloader   : [ID: 32504, Host: 172.20.0.1] Downloader error: Error while adding NZB(s): I/O error on POST request for "http://localhost:3000/api": timeout
> 2026-01-17 22:09:50.820 ERROR --- [http-nio-0.0.0.0-5] o.n.downloading.downloaders.Downloader   : [Host: 172.20.0.1] Downloader error: Error while adding NZB(s): I/O error on POST request for "http://localhost:3000/api": timeout

**Comment by nzbdav-dev** [comment]
Thank you for the additional details @huplo-glitch 

----

For my own future reference, I'm pasting a related conversation from discord

<img width="400" height="664" alt="Image" src="https://github.com/user-attachments/assets/01a8e9d9-c03c-4647-9aad-a8d31e064796" />

**Comment by huplo-glitch** [comment]
Pleasure! Happy to continue testing, just shout. :)

**Comment by nzbdav-dev** [comment]
Should (hopefully 🤞) be resolved now in [0.5.24](https://github.com/nzbdav-dev/nzbdav/pkgs/container/nzbdav).
I'm closing the issue, but feel free to reopen if there's any problem :)
